name: Pull request

on:
  push:
    branches:
      - master
  pull_request:
env:
  resourceRunID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  Build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        api: [ 34 ]
        abi: [ x86_64 ]
        emulatorApi: [ 14 ]
        tag: [ 'google_apis' ]
    #        include:
    #          - os: macOS-latest
    #            abi: x86_64
    #            api: 28
    #            emulatorApi: [ 9 ]
    #            tag: 'default'
    steps:
      - name: kvm support
        run: |
          egrep -c '(vmx|svm)' /proc/cpuinfo
          id
          sudo adduser $USER kvm
          sudo chown -R $USER /dev/kvm
          id
      - name: prepare
        run: |
          sudo apt-get update && sudo apt-get install -y exiftool imagemagick xdg-utils libimage-exiftool-perl zsh jq xorg
      #          brew install exiftool imagemagick
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v4
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Code checks
        run: ./gradlew assembleDebug

  Check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Websocket-Lint-report
          path: |
            ./**/build/reports/lint-results*.html
